#Common Response Messages
#Successful Responses

OK_STATUS = 200 
CREATED_STATUS = 201 
ACCEPTED_STATUS = 202  

# Client Bad Input Error Responses

BAD_REQUEST_STATUS = 400
UNAUTHORIZED_STATUS = 401
NOT_FOUND_STATUS = 404

# Server Error Responses

INTERNAL_SERVER_ERROR_STATUS = 500 
BAD_GATEWAY_STATUS = 502

# Specific Error Responses (Client Error)

WRONG_LOGIN_INFO_STATUS = 450
NOT_ENOUGH_FUNDS_STATUS = 451 
WRONG_CARD_NUMBER_STATUS = 452
USER_DOES_NOT_EXIST_STATUS = 453
USER_ALREADY_EXISTS_STATUS = 454 
RESTAURANT_DOES_NOT_EXIST_STATUS = 455
RESERVATION_DOES_NOT_EXIST_STATUS = 456
INSUFICIENT_FUNDS_STATUS = 457
CARD_ALREADY_REDDEMED_STATUS = 458
INSUFICIENT_POINTS_STATUS = 459